#
# Macro file for "Hadr06.cc"
#
#
/control/verbose 1
/run/verbose 1
#
#/testhadr/det/setIsotopeMat Li7 3 7 1.85 g/cm3
###/testhadr/det/setIsotopeMat Be9 4 9 1.85 g/cm3
/testhadr/det/setRadius
/testhadr/det/setMat
#
###/testhadr/phys/thermalScattering true
#
/run/initialize
#
/process/list
#
/gun/particle neutron
/gun/energy
#
/analysis/setFileName
/analysis/h1/set 1  100  0. 15. MeV	#Edep
/analysis/h1/set 2 100  0.   105. cm	#Edep profile
/analysis/h1/set 3  100  0. 15. MeV	#Eflow
/analysis/h1/set 4  100  0. 15. MeV	#gamma
/analysis/h1/set 6
/analysis/h1/set 9  100  0. 15. MeV	#alphas
/analysis/h1/set 10  100  0. 15. MeV	#generic ions
/analysis/h1/setAscii 6
#
/run/printProgress
#
/run/beamOn
